name: Android Release CI

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Decode Keystore
        run: echo "${{ secrets.SIGNING_KEY }}" | base64 --decode > release.jks

      - name: Build Release APK
        # 这里的多行命令使用 \ 来换行，比 > 更不容易出错
        run: |
          ./gradlew assembleRelease \
          -Pandroid.injected.signing.store.file=$(pwd)/release.jks \
          -Pandroid.injected.signing.store.password=${{ secrets.KEY_STORE_PASSWORD }} \
          -Pandroid.injected.signing.key.alias=${{ secrets.ALIAS }} \
          -Pandroid.injected.signing.key.password=${{ secrets.KEY_PASSWORD }}

      #- name: Rename APK
        # 使用 *.apk 匹配该目录下任何名字的 APK 文件
        #run: mv app/build/outputs/apk/release/*.apk app/build/outputs/apk/release/SuwayomiGO-${{ github.ref_name }}.apk

      # 2. 修改 Create Release 步骤
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          # 使用通配符直接上传，GitHub 会自动使用文件的真实名字
          files: app/build/outputs/apk/release/*.apk
          name: SuwayomiGO ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}